---
- name: setup an instance to run flask
  hosts: all
  gather_facts: False
  
  pre_tasks:
    - name: install python 2
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
  tasks:
    - name: install apache
      apt:
        name: apache2
        state: present
    - name: install mod_wsgi
      raw: sudo apt-get install libapache2-mod-wsgi python-dev
    - name: enable mod_wsgi
      raw: sudo a2enmod wsgi 
    - name: clone flask repo
      git:
        repo: 'https://github.com/ahouyang/ansible-flask.git'
        dest: /var/www/FlaskApp
    - name: move FlaskApp.conf to apache sites-available folder
      copy: 
        remote_src: yes
        src: /var/www/FlaskApp/ansible-flask/setup/FlaskApp.conf
        dest: /etc/apache2/sites-available/
    - name: move flaskapp.wsgi to correct location
      copy: 
        remote_src: yes
        src: /var/www/FlaskApp/ansible-flask/setup/flaskapp.wsgi
        dest: /var/www/FlaskApp/
    - name: copy git repo to FlaskApp/
      copy: 
        remote_src: yes
        src: /var/www/FlaskApp/ansible-flask/
        dest: /var/www/FlaskApp/FlaskApp/
    - pip:
        name:
          - flask
          - flask-restful
          - pymongo
          - pika
    - name: enable flask virtualhost
      raw: a2ensite FlaskApp.conf
    - name: disable default host
      raw: a2dissite 000-default.conf
    - name: restart apache
      raw: sudo service apache2 restart

